export type ToolCategory =
  | "PDF"
  | "Image"
  | "Calculator"
  | "Text"
  | "Converter"
  | "Generator"
  | "Security"
  | "Developer"
  | "Health"
  | "Finance"
  | "Math";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  metaDescription?: string;  // SEO-optimised, 140–160 chars
  category: ToolCategory;
  icon: string;        // Lucide icon name
  keywords: string[];
  relatedSlugs?: string[];
  isNew?: boolean;
  isPro?: boolean;
}

export const tools: Tool[] = [
  // ─── PDF ─────────────────────────────────────────────────────────────────
  {
    slug: "pdf-merge",
    name: "PDF Merge",
    description: "Combine multiple PDF files into one in seconds.",
    metaDescription: "Free online PDF merger — combine multiple PDF files into one document instantly. No upload required, 100% in-browser. Drag, reorder, and merge PDFs securely.",
    category: "PDF",
    icon: "FilePlus2",
    keywords: ["pdf", "merge", "combine", "join"],
    relatedSlugs: ["pdf-split", "images-to-pdf", "pdf-to-images"],
  },
  {
    slug: "pdf-split",
    name: "PDF Split",
    description: "Extract pages or split a PDF into multiple files.",
    metaDescription: "Split a PDF into individual pages or extract a custom page range — free and in-browser. No file upload needed. Download split PDFs instantly.",
    category: "PDF",
    icon: "Scissors",
    keywords: ["pdf", "split", "extract", "pages"],
    relatedSlugs: ["pdf-merge", "pdf-to-images", "images-to-pdf"],
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    description: "Convert each PDF page to a high-quality PNG/JPG.",
    metaDescription: "Convert PDF pages to high-quality PNG or JPG images for free. Runs entirely in your browser — no upload, no registration. Fast PDF to image converter.",
    category: "PDF",
    icon: "Image",
    keywords: ["pdf", "image", "convert", "png", "jpg"],
    relatedSlugs: ["pdf-split", "image-compress", "image-convert"],
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    description: "Turn JPG/PNG images into a single PDF document.",
    metaDescription: "Convert JPG, PNG, or WebP images into a PDF document online for free. Reorder pages, choose A4 or Letter size, and download instantly — no upload needed.",
    category: "PDF",
    icon: "FileImage",
    keywords: ["image", "pdf", "convert"],
    relatedSlugs: ["pdf-merge", "image-compress", "image-resize"],
  },

  // ─── Image ───────────────────────────────────────────────────────────────
  {
    slug: "image-compress",
    name: "Image Compress",
    description: "Reduce image file size without visible quality loss.",
    metaDescription: "Compress JPG, PNG, and WebP images online for free — reduce file size by up to 90% without visible quality loss. Batch compression, fully in-browser.",
    category: "Image",
    icon: "Minimize2",
    keywords: ["image", "compress", "reduce", "optimize", "jpg", "png", "webp"],
    relatedSlugs: ["image-resize", "image-convert", "image-crop"],
  },
  {
    slug: "image-resize",
    name: "Image Resize",
    description: "Resize images to any dimension or percentage.",
    metaDescription: "Resize images online for free — enter exact pixel dimensions or a percentage, lock aspect ratio, and download instantly. Supports JPG, PNG, and WebP.",
    category: "Image",
    icon: "Expand",
    keywords: ["image", "resize", "scale", "dimension"],
    relatedSlugs: ["image-compress", "image-crop", "image-convert"],
  },
  {
    slug: "image-crop",
    name: "Image Crop",
    description: "Crop images to a custom aspect ratio or pixel size.",
    metaDescription: "Crop images online to any size or aspect ratio — 1:1, 4:3, 16:9, or freeform. Free in-browser image cropper with instant PNG download.",
    category: "Image",
    icon: "Crop",
    keywords: ["image", "crop", "trim"],
    relatedSlugs: ["image-resize", "image-compress", "image-watermark"],
  },
  {
    slug: "image-convert",
    name: "Image Convert",
    description: "Convert between JPG, PNG, WebP, GIF, and more.",
    metaDescription: "Convert images between JPG, PNG, WebP, and GIF formats for free online. Adjust quality, preview before download. No upload — runs entirely in your browser.",
    category: "Image",
    icon: "RefreshCw",
    keywords: ["image", "convert", "format", "jpg", "png", "webp", "gif"],
    relatedSlugs: ["image-compress", "image-resize", "image-watermark"],
  },
  {
    slug: "image-watermark",
    name: "Image Watermark",
    description: "Add a text or logo watermark to your images.",
    metaDescription: "Add a custom text watermark to your images online — choose position, opacity, font size, color, and rotation. Free, in-browser, no upload needed.",
    category: "Image",
    icon: "Stamp",
    keywords: ["image", "watermark", "logo", "text"],
    relatedSlugs: ["image-compress", "image-resize", "image-crop"],
    isNew: true,
  },
  {
    slug: "bg-remover",
    name: "Background Remover",
    description: "Remove image backgrounds 100% in-browser.",
    metaDescription: "Remove image backgrounds automatically for free — get a clean transparent PNG in seconds. 100% in-browser, no upload, no sign-up required.",
    category: "Image",
    icon: "Eraser",
    keywords: ["background", "remove", "transparent", "png"],
    isNew: true,
  },

  // ─── Calculator ──────────────────────────────────────────────────────────
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index with metric or imperial units.",
    metaDescription: "Free BMI calculator — calculate your Body Mass Index using metric or imperial units. Get WHO weight classification, healthy range, and visual gauge instantly.",
    category: "Calculator",
    icon: "Weight",
    keywords: ["bmi", "body mass index", "health", "weight"],
    relatedSlugs: ["calorie-calculator", "age-calculator", "percentage-calculator"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Compute monthly payments, interest, and amortization.",
    metaDescription: "Free loan and mortgage calculator — compute monthly payments, total interest, and full amortization schedule. Supports any loan amount, rate, and term.",
    category: "Calculator",
    icon: "Landmark",
    keywords: ["loan", "mortgage", "interest", "payment", "finance"],
    relatedSlugs: ["mortgage-calculator", "compound-interest", "tip-calculator"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Find percentages, increase/decrease, and ratios instantly.",
    metaDescription: "Free percentage calculator — find X% of a number, what percentage one number is of another, and calculate percentage increase or decrease instantly.",
    category: "Calculator",
    icon: "Percent",
    keywords: ["percentage", "percent", "ratio", "calculator"],
    relatedSlugs: ["tip-calculator", "discount-calculator", "vat-calculator"],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, days, and hours.",
    metaDescription: "Calculate your exact age in years, months, days, hours, and minutes. Find your next birthday countdown, day of birth, zodiac sign, and more — free online.",
    category: "Calculator",
    icon: "CalendarDays",
    keywords: ["age", "birthday", "date", "calculator"],
    relatedSlugs: ["date-difference", "due-date-calculator", "bmi-calculator"],
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Split bills and calculate tips for any group size.",
    metaDescription: "Free tip calculator — calculate tip amount, total bill, and per-person split for any group size. Choose from preset tip percentages or enter a custom amount.",
    category: "Calculator",
    icon: "Receipt",
    keywords: ["tip", "bill", "split", "restaurant"],
    relatedSlugs: ["percentage-calculator", "discount-calculator", "vat-calculator"],
  },
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    description: "Full-featured scientific calculator with history.",
    metaDescription: "Free online scientific calculator with sin, cos, tan, log, sqrt, exponents, and full calculation history. Supports DEG/RAD mode and keyboard input.",
    category: "Calculator",
    icon: "Calculator",
    keywords: ["calculator", "scientific", "math", "trig"],
    relatedSlugs: ["percentage-calculator", "statistics-calculator", "grade-calculator"],
  },

  // ─── Converter ───────────────────────────────────────────────────────────
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, weight, temperature, speed, and more.",
    metaDescription: "Free unit converter — convert length, weight, temperature, speed, area, volume, and data units instantly. Supports metric and imperial systems.",
    category: "Converter",
    icon: "ArrowLeftRight",
    keywords: ["unit", "convert", "length", "weight", "temperature"],
    relatedSlugs: ["currency-converter", "color-converter", "binary-hex"],
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL, HSV, and CMYK.",
    metaDescription: "Free color converter — instantly convert colors between HEX, RGB, HSL, and CMYK formats. Live color preview with one-click copy for each format.",
    category: "Converter",
    icon: "Palette",
    keywords: ["color", "hex", "rgb", "hsl", "convert"],
    relatedSlugs: ["color-palette", "unit-converter", "css-minifier"],
  },
  {
    slug: "base64",
    name: "Base64 Encode/Decode",
    description: "Encode or decode Base64 strings and files.",
    metaDescription: "Free Base64 encoder and decoder online — encode text or files to Base64, or decode Base64 strings back to plain text. Supports UTF-8 and binary files.",
    category: "Converter",
    icon: "Binary",
    keywords: ["base64", "encode", "decode"],
    relatedSlugs: ["binary-hex", "hash-generator", "url-encoder"],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Validate, format, and minify JSON with syntax highlighting.",
    metaDescription: "Free online JSON formatter, validator, and minifier — pretty-print JSON with 2-space indentation or minify for production. Instant error detection with line numbers.",
    category: "Developer",
    icon: "Braces",
    keywords: ["json", "format", "validate", "minify", "pretty"],
    relatedSlugs: ["csv-json", "regex-tester", "sql-formatter"],
  },

  // ─── Text ─────────────────────────────────────────────────────────────────
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and reading time.",
    metaDescription: "Free online word counter — count words, characters (with and without spaces), sentences, paragraphs, and estimated reading time. Updates live as you type.",
    category: "Text",
    icon: "FileText",
    keywords: ["word", "count", "character", "text", "reading time"],
    relatedSlugs: ["case-converter", "text-diff", "keyword-density"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to UPPER, lower, Title, or camelCase.",
    metaDescription: "Free text case converter — instantly convert text to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, or kebab-case online.",
    category: "Text",
    icon: "CaseSensitive",
    keywords: ["case", "upper", "lower", "title", "camel", "text"],
    relatedSlugs: ["word-counter", "text-to-slug", "text-diff"],
  },
  {
    slug: "text-diff",
    name: "Text Diff Checker",
    description: "Compare two texts and highlight differences.",
    metaDescription: "Free online text diff tool — compare two texts side by side and highlight added, removed, and changed lines. Great for spotting edits in documents or code.",
    category: "Text",
    icon: "Diff",
    keywords: ["diff", "compare", "text", "difference"],
    relatedSlugs: ["word-counter", "markdown-html", "case-converter"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text in paragraphs or words.",
    metaDescription: "Free Lorem Ipsum generator — generate placeholder text by paragraphs, sentences, or words. Optionally start with the classic 'Lorem ipsum dolor sit amet' opening.",
    category: "Generator",
    icon: "AlignLeft",
    keywords: ["lorem", "ipsum", "placeholder", "text", "generator"],
    relatedSlugs: ["word-counter", "markdown-html", "fake-data"],
  },

  // ─── Generator ────────────────────────────────────────────────────────────
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, email, or Wi-Fi.",
    metaDescription: "Free QR code generator — create QR codes for URLs, text, email, or Wi-Fi credentials. Customize size, colors, and error correction. Download as PNG or SVG.",
    category: "Generator",
    icon: "QrCode",
    keywords: ["qr", "code", "generator", "scan", "barcode"],
    relatedSlugs: ["barcode-generator", "uuid-generator", "url-encoder"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Create strong, secure passwords with custom rules.",
    metaDescription: "Free strong password generator — create secure random passwords with custom length, uppercase, numbers, and symbols. Includes password strength indicator.",
    category: "Security",
    icon: "KeyRound",
    keywords: ["password", "generator", "secure", "random"],
    relatedSlugs: ["hash-generator", "uuid-generator", "base64"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate v4 UUIDs in bulk for development use.",
    metaDescription: "Free UUID v4 generator — generate up to 100 UUIDs instantly in lowercase, uppercase, or no-dash format. Copy individually or all at once. No install needed.",
    category: "Generator",
    icon: "Hash",
    keywords: ["uuid", "guid", "generator", "unique", "id"],
    relatedSlugs: ["qr-generator", "hash-generator", "fake-data"],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate harmonious color palettes from any base color.",
    metaDescription: "Free color palette generator — create complementary, triadic, analogous, and monochromatic palettes from any base color. Export as CSS variables instantly.",
    category: "Generator",
    icon: "Pipette",
    keywords: ["color", "palette", "generate", "design"],
    relatedSlugs: ["color-converter", "color-picker", "css-minifier"],
    isNew: true,
  },
  {
    slug: "pomodoro",
    name: "Pomodoro Timer",
    description: "Focus timer with 25-min work sessions and break alerts.",
    metaDescription: "Free Pomodoro timer online — 25-minute focus sessions with short and long break intervals. Customizable durations, audio alerts, and session tracking.",
    category: "Calculator",
    icon: "Timer",
    keywords: ["pomodoro", "timer", "focus", "productivity"],
    relatedSlugs: ["stopwatch", "countdown-timer", "productivity"],
  },

  // ─── Security ────────────────────────────────────────────────────────────
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes.",
    metaDescription: "Free hash generator — compute MD5, SHA-1, SHA-256, and SHA-512 hashes for text or files online. Supports HMAC. All processing done in your browser.",
    category: "Security",
    icon: "ShieldCheck",
    keywords: ["hash", "md5", "sha", "sha256", "security", "checksum"],
    relatedSlugs: ["password-generator", "base64", "uuid-generator"],
  },

  // ─── Developer ───────────────────────────────────────────────────────────
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Write, test, and debug regular expressions live.",
    metaDescription: "Free online regex tester — write and test regular expressions with live match highlighting, match list, group captures, and flag toggles (g, i, m, s, u).",
    category: "Developer",
    icon: "Code2",
    keywords: ["regex", "regular expression", "test", "developer"],
    relatedSlugs: ["json-formatter", "text-diff", "word-counter"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    description: "Minify CSS for faster page loads.",
    metaDescription: "Free online CSS minifier — remove whitespace, comments, and redundant code to shrink your CSS file size for faster page loads. Instant results, no upload.",
    category: "Developer",
    icon: "Zap",
    keywords: ["css", "minify", "compress", "developer"],
    relatedSlugs: ["json-formatter", "sql-formatter", "html-entities"],
  },

  // ─── Converter (new) ─────────────────────────────────────────────────────
  {
    slug: "csv-json",
    name: "CSV ↔ JSON Converter",
    description: "Convert CSV to JSON or JSON to CSV instantly.",
    metaDescription: "Free CSV to JSON converter and JSON to CSV converter online. Paste your data, choose direction, copy or download the result. No upload, fully in-browser.",
    category: "Converter",
    icon: "Table",
    keywords: ["csv", "json", "convert", "data", "table"],
    relatedSlugs: ["json-formatter", "markdown-html", "word-counter"],
    isNew: true,
  },
  {
    slug: "roman-numeral",
    name: "Roman Numeral Converter",
    description: "Convert between Roman numerals and Arabic numbers.",
    metaDescription: "Free Roman numeral converter — convert numbers to Roman numerals (I, V, X, L, C, D, M) and back. Supports numbers from 1 to 3,999 instantly.",
    category: "Converter",
    icon: "Type",
    keywords: ["roman", "numeral", "convert", "number"],
    relatedSlugs: ["number-to-words", "binary-hex", "scientific-calculator"],
    isNew: true,
  },
  {
    slug: "number-to-words",
    name: "Number to Words",
    description: "Convert numbers into English words for cheques and documents.",
    metaDescription: "Convert numbers to words in English online — useful for writing cheques, legal documents, and invoices. Supports numbers up to trillions.",
    category: "Converter",
    icon: "Spell",
    keywords: ["number", "words", "convert", "spell", "cheque"],
    relatedSlugs: ["roman-numeral", "binary-hex", "word-counter"],
    isNew: true,
  },
  {
    slug: "binary-hex",
    name: "Binary / Hex / Octal Converter",
    description: "Convert between binary, hexadecimal, octal, and decimal.",
    metaDescription: "Free number base converter — convert between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16) instantly.",
    category: "Developer",
    icon: "Binary",
    keywords: ["binary", "hex", "hexadecimal", "octal", "decimal", "base", "convert"],
    relatedSlugs: ["base64", "unit-converter", "roman-numeral"],
    isNew: true,
  },
  {
    slug: "markdown-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to clean HTML with live preview.",
    metaDescription: "Free Markdown to HTML converter with live preview — paste Markdown, see rendered HTML instantly. Copy raw HTML or preview output. No install needed.",
    category: "Developer",
    icon: "FileCode",
    keywords: ["markdown", "html", "convert", "preview", "md"],
    relatedSlugs: ["word-counter", "text-diff", "html-entities"],
    isNew: true,
  },
  {
    slug: "keyword-density",
    name: "Keyword Density Checker",
    description: "Analyse keyword frequency and density in any text.",
    metaDescription: "Free keyword density checker — paste any text and instantly see word frequency, density %, and top keywords. Essential for SEO content optimization.",
    category: "Text",
    icon: "BarChart2",
    keywords: ["keyword", "density", "seo", "frequency", "text", "analysis"],
    relatedSlugs: ["word-counter", "readability-checker", "text-to-slug"],
    isNew: true,
  },
  {
    slug: "fake-data",
    name: "Fake Data Generator",
    description: "Generate realistic fake names, emails, addresses, and more.",
    metaDescription: "Free fake data generator — generate realistic test data: names, emails, phone numbers, addresses, and UUIDs. Perfect for developers and QA testers.",
    category: "Generator",
    icon: "UserRound",
    keywords: ["fake", "data", "generator", "test", "mock", "name", "email"],
    relatedSlugs: ["uuid-generator", "email-validator", "lorem-ipsum"],
    isNew: true,
  },
  {
    slug: "email-validator",
    name: "Email Validator",
    description: "Validate email addresses for correct format instantly.",
    metaDescription: "Free email validator — check if an email address is correctly formatted. Validate single or bulk email addresses instantly. No sign-up required.",
    category: "Developer",
    icon: "Mail",
    keywords: ["email", "validate", "check", "format", "verify"],
    relatedSlugs: ["word-counter", "keyword-density", "fake-data"],
    isNew: true,
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate Code128, EAN-13, and UPC barcodes instantly.",
    metaDescription: "Free barcode generator — create Code128, EAN-13, and UPC-A barcodes online. Download as PNG or SVG. No registration, runs entirely in your browser.",
    category: "Generator",
    icon: "ScanBarcode",
    keywords: ["barcode", "ean", "upc", "code128", "generator"],
    relatedSlugs: ["qr-generator", "uuid-generator", "fake-data"],
    isNew: true,
  },

  // ─── Math ────────────────────────────────────────────────────────────────
  {
    slug: "statistics-calculator",
    name: "Statistics Calculator",
    description: "Calculate mean, median, mode, standard deviation, and more.",
    metaDescription: "Free statistics calculator — compute mean, median, mode, range, variance, standard deviation, and more from a list of numbers. Instant results.",
    category: "Math",
    icon: "Sigma",
    keywords: ["statistics", "mean", "median", "mode", "standard deviation", "variance"],
    relatedSlugs: ["grade-calculator", "scientific-calculator", "compound-interest"],
    isNew: true,
  },

  // ─── Finance ─────────────────────────────────────────────────────────────
  {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest growth with charts.",
    metaDescription: "Free compound interest calculator — see how investments grow over time with compound interest. Enter principal, rate, frequency, and years to visualise returns.",
    category: "Finance",
    icon: "TrendingUp",
    keywords: ["compound interest", "investment", "savings", "finance", "calculator"],
    relatedSlugs: ["investment-return", "mortgage-calculator", "loan-calculator"],
    isNew: true,
  },
  {
    slug: "investment-return",
    name: "Investment Return Calculator",
    description: "Calculate ROI and total returns on any investment.",
    metaDescription: "Free investment return calculator — calculate ROI, total return, and annualised return on any investment. Compare simple vs compound growth instantly.",
    category: "Finance",
    icon: "DollarSign",
    keywords: ["investment", "roi", "return", "finance", "calculator"],
    relatedSlugs: ["compound-interest", "mortgage-calculator", "statistics-calculator"],
    isNew: true,
  },
  {
    slug: "grade-calculator",
    name: "Grade / GPA Calculator",
    description: "Calculate weighted grades and GPA for any course.",
    metaDescription: "Free grade and GPA calculator — add assignments with weights to compute your overall grade. Supports letter grades, percentages, and GPA on 4.0 scale.",
    category: "Calculator",
    icon: "GraduationCap",
    keywords: ["grade", "gpa", "calculator", "weighted", "student", "school"],
    relatedSlugs: ["statistics-calculator", "age-calculator", "percentage-calculator"],
    isNew: true,
  },

  // ─── Health ──────────────────────────────────────────────────────────────
  {
    slug: "calorie-calculator",
    name: "Calorie & Macro Calculator",
    description: "Calculate daily calorie needs and macronutrient ratios.",
    metaDescription: "Free calorie and macro calculator — find your TDEE (total daily energy expenditure), ideal protein, carb, and fat intake based on your goal and activity level.",
    category: "Health",
    icon: "Flame",
    keywords: ["calorie", "macro", "tdee", "protein", "carbs", "fat", "diet", "fitness"],
    relatedSlugs: ["bmi-calculator", "due-date-calculator", "age-calculator"],
    isNew: true,
  },
  {
    slug: "due-date-calculator",
    name: "Pregnancy Due Date Calculator",
    description: "Calculate your pregnancy due date and week-by-week milestones.",
    metaDescription: "Free pregnancy due date calculator — enter your last period date or conception date to find your due date, current week, trimester, and key milestones.",
    category: "Health",
    icon: "Baby",
    keywords: ["pregnancy", "due date", "calculator", "trimester", "weeks pregnant"],
    relatedSlugs: ["date-difference", "age-calculator", "calorie-calculator"],
    isNew: true,
  },
  {
    slug: "date-difference",
    name: "Date Difference Calculator",
    description: "Calculate the exact difference between two dates.",
    metaDescription: "Free date difference calculator — find the exact number of days, weeks, months, and years between any two dates. Great for deadlines, anniversaries, and contracts.",
    category: "Calculator",
    icon: "CalendarRange",
    keywords: ["date", "difference", "days", "between", "calculator"],
    relatedSlugs: ["due-date-calculator", "age-calculator", "timezone-converter"],
    isNew: true,
  },

  // ─── Developer (Phase 2) ─────────────────────────────────────────────────
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Token header, payload, and signature.",
    metaDescription: "Free JWT decoder — paste any JSON Web Token to instantly view the header, payload claims, and expiry. Works offline, nothing is sent to a server.",
    category: "Developer",
    icon: "KeyRound",
    keywords: ["jwt", "json web token", "decode", "auth", "bearer", "token"],
    relatedSlugs: ["hash-generator", "base64", "url-encoder"],
    isNew: true,
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Beautify and format SQL queries for readability.",
    metaDescription: "Free SQL formatter — paste messy SQL and get beautifully indented, readable queries back. Supports SELECT, INSERT, UPDATE, DELETE, and JOINs. 100% in-browser.",
    category: "Developer",
    icon: "Database",
    keywords: ["sql", "formatter", "beautify", "format", "query", "database"],
    relatedSlugs: ["json-formatter", "csv-json", "regex-tester"],
    isNew: true,
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode or decode URLs and query string parameters instantly.",
    metaDescription: "Free URL encoder and decoder — encode special characters for safe URLs or decode percent-encoded strings. Supports full URLs and individual query parameters.",
    category: "Developer",
    icon: "Link",
    keywords: ["url", "encode", "decode", "percent", "uri", "query string"],
    relatedSlugs: ["base64", "jwt-decoder", "html-entities"],
    isNew: true,
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Parse and explain cron expressions in plain English.",
    metaDescription: "Free cron expression parser — enter a cron schedule (5 or 6 fields) and get a human-readable explanation plus the next 10 run times. Instant, no server needed.",
    category: "Developer",
    icon: "Clock4",
    keywords: ["cron", "crontab", "schedule", "expression", "parser", "linux"],
    relatedSlugs: ["regex-tester", "json-formatter", "stopwatch"],
    isNew: true,
  },

  // ─── Text (Phase 2) ──────────────────────────────────────────────────────
  {
    slug: "readability-checker",
    name: "Readability Checker",
    description: "Measure text readability using Flesch-Kincaid and other scores.",
    metaDescription: "Free readability checker — calculate Flesch Reading Ease, Flesch-Kincaid Grade, Gunning Fog, SMOG, and ARI scores for any text. Improve your writing instantly.",
    category: "Text",
    icon: "BookOpen",
    keywords: ["readability", "flesch", "kincaid", "gunning fog", "reading level", "grade"],
    relatedSlugs: ["word-counter", "keyword-density", "text-to-slug"],
    isNew: true,
  },
  {
    slug: "text-to-slug",
    name: "Text to Slug",
    description: "Convert any text into a URL-friendly slug.",
    metaDescription: "Free slug generator — convert titles and text into clean, lowercase, URL-friendly slugs. Removes special characters, handles accents, and supports custom separators.",
    category: "Text",
    icon: "Link2",
    keywords: ["slug", "url", "permalink", "seo", "sanitize", "kebab-case"],
    relatedSlugs: ["case-converter", "keyword-density", "url-encoder"],
    isNew: true,
  },
  {
    slug: "html-entities",
    name: "HTML Entities Encoder",
    description: "Encode and decode HTML special characters and entities.",
    metaDescription: "Free HTML entity encoder/decoder — convert <, >, &, quotes, and Unicode characters to HTML entities or decode them back. Instant, browser-only.",
    category: "Developer",
    icon: "Code2",
    keywords: ["html", "entities", "encode", "decode", "escape", "unescape", "special characters"],
    relatedSlugs: ["markdown-html", "url-encoder", "base64"],
    isNew: true,
  },

  // ─── Finance (Phase 2) ───────────────────────────────────────────────────
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert between 30+ world currencies with up-to-date rates.",
    metaDescription: "Free currency converter — convert between 30+ currencies including USD, EUR, GBP, JPY, INR, AUD, and more. Fast, browser-based currency conversion tool.",
    category: "Finance",
    icon: "DollarSign",
    keywords: ["currency", "converter", "exchange rate", "usd", "eur", "forex"],
    relatedSlugs: ["vat-calculator", "discount-calculator", "mortgage-calculator"],
    isNew: true,
  },
  {
    slug: "vat-calculator",
    name: "VAT Calculator",
    description: "Calculate VAT / sales tax — add or remove tax from any amount.",
    metaDescription: "Free VAT calculator — add or remove tax from any amount. Supports custom tax rates (VAT, GST, sales tax). Instant calculation for invoicing and shopping.",
    category: "Finance",
    icon: "Receipt",
    keywords: ["vat", "tax", "gst", "sales tax", "calculator", "invoice"],
    relatedSlugs: ["currency-converter", "discount-calculator", "percentage-calculator"],
    isNew: true,
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Calculate monthly payments, total interest, and amortization schedule.",
    metaDescription: "Free mortgage calculator — estimate monthly payments, total interest paid, and view a full amortization schedule. Supports extra monthly payments and different terms.",
    category: "Finance",
    icon: "Home",
    keywords: ["mortgage", "loan", "amortization", "home loan", "monthly payment", "interest"],
    relatedSlugs: ["loan-calculator", "compound-interest", "discount-calculator"],
    isNew: true,
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    description: "Calculate sale price, savings amount, and discount percentage.",
    metaDescription: "Free discount calculator — find the sale price after a % off, calculate what discount percentage was applied, or determine the original price from a sale price.",
    category: "Finance",
    icon: "Tag",
    keywords: ["discount", "sale", "percent off", "savings", "price", "coupon"],
    relatedSlugs: ["vat-calculator", "percentage-calculator", "tip-calculator"],
    isNew: true,
  },

  // ─── Utility (Phase 2) ───────────────────────────────────────────────────
  {
    slug: "stopwatch",
    name: "Stopwatch",
    description: "Precise stopwatch with lap times and split tracking.",
    metaDescription: "Free online stopwatch with lap and split times. Tracks up to 100 laps with average, fastest, and slowest lap stats. Works offline, no install needed.",
    category: "Calculator",
    icon: "Timer",
    keywords: ["stopwatch", "timer", "lap", "split", "track", "time"],
    relatedSlugs: ["countdown-timer", "pomodoro", "date-difference"],
    isNew: true,
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Set a countdown timer with audio alert when time is up.",
    metaDescription: "Free countdown timer — set hours, minutes, and seconds, then get an audio and visual alert when time expires. Works in any browser tab, no install needed.",
    category: "Calculator",
    icon: "AlarmClock",
    keywords: ["countdown", "timer", "alarm", "clock", "minutes", "seconds"],
    relatedSlugs: ["stopwatch", "pomodoro", "date-difference"],
    isNew: true,
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    description: "Calculate and convert aspect ratios for images and videos.",
    metaDescription: "Free aspect ratio calculator — find missing dimensions, convert between ratios (16:9, 4:3, 1:1, etc.), and compare ratios. Great for designers and video editors.",
    category: "Calculator",
    icon: "RectangleHorizontal",
    keywords: ["aspect ratio", "resolution", "16:9", "4:3", "image", "video", "dimensions"],
    relatedSlugs: ["image-resize", "image-crop", "unit-converter"],
    isNew: true,
  },
  {
    slug: "timezone-converter",
    name: "Time Zone Converter",
    description: "Convert times across world time zones instantly.",
    metaDescription: "Free time zone converter — convert a specific time between any two world time zones. Great for scheduling meetings across countries. Supports DST automatically.",
    category: "Calculator",
    icon: "Globe",
    keywords: ["timezone", "time zone", "convert", "utc", "gmt", "world clock", "dst"],
    relatedSlugs: ["date-difference", "age-calculator", "stopwatch"],
    isNew: true,
  },

  // ─── Phase 3 — Developer ─────────────────────────────────────────────────
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Format, minify, and validate XML documents instantly.",
    metaDescription: "Free XML formatter and validator — beautify messy XML with proper indentation, minify for production, and validate structure. No upload, runs in your browser.",
    category: "Developer",
    icon: "Code",
    keywords: ["xml", "formatter", "beautify", "minify", "validate", "pretty print"],
    relatedSlugs: ["json-formatter", "yaml-json", "sql-formatter"],
    isNew: true,
  },
  {
    slug: "yaml-json",
    name: "YAML ↔ JSON Converter",
    description: "Convert YAML to JSON and JSON to YAML instantly.",
    metaDescription: "Free YAML to JSON and JSON to YAML converter — paste and convert between formats instantly. Validates syntax and shows errors. No upload, 100% in-browser.",
    category: "Developer",
    icon: "FileCode",
    keywords: ["yaml", "json", "convert", "yml", "config", "formatter"],
    relatedSlugs: ["json-formatter", "xml-formatter", "csv-json"],
    isNew: true,
  },
  {
    slug: "diff-checker",
    name: "Text Diff Checker",
    description: "Compare two texts side-by-side and highlight differences.",
    metaDescription: "Free online diff checker — compare two texts, code files, or documents side-by-side. Highlights added, removed, and changed lines. No upload needed.",
    category: "Developer",
    icon: "GitCompare",
    keywords: ["diff", "compare", "text", "code", "difference", "side by side", "merge"],
    relatedSlugs: ["text-diff", "json-formatter", "xml-formatter"],
    isNew: true,
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description: "Pick, convert, and explore colors in HEX, RGB, HSL, and CMYK.",
    metaDescription: "Free online color picker — select any color and instantly convert between HEX, RGB, HSL, CMYK, and HSV. Generate shades, tints, and complementary colors.",
    category: "Developer",
    icon: "Pipette",
    keywords: ["color picker", "hex", "rgb", "hsl", "cmyk", "color converter", "palette"],
    relatedSlugs: ["color-converter", "color-palette", "css-minifier"],
    isNew: true,
  },

  // ─── Phase 3 — Fun / Generator ───────────────────────────────────────────
  {
    slug: "coin-flip",
    name: "Coin Flip",
    description: "Flip a virtual coin — heads or tails, with flip history.",
    metaDescription: "Free virtual coin flip — get an instant heads or tails result with animation. Tracks flip history and streak counts. No bias, cryptographically random.",
    category: "Generator",
    icon: "CircleDot",
    keywords: ["coin flip", "heads or tails", "random", "flip coin", "coin toss"],
    relatedSlugs: ["dice-roller", "random-picker", "uuid-generator"],
    isNew: true,
  },
  {
    slug: "dice-roller",
    name: "Dice Roller",
    description: "Roll any dice — D4, D6, D8, D10, D12, D20, or custom.",
    metaDescription: "Free online dice roller — roll D4, D6, D8, D10, D12, D20, or any custom-sided die. Roll multiple dice at once. Perfect for tabletop RPGs and board games.",
    category: "Generator",
    icon: "Dices",
    keywords: ["dice roller", "d20", "d6", "rpg", "random", "tabletop", "dungeons dragons"],
    relatedSlugs: ["coin-flip", "random-picker", "uuid-generator"],
    isNew: true,
  },
  {
    slug: "random-picker",
    name: "Random Picker",
    description: "Pick a random item from your list — ideal for decisions and giveaways.",
    metaDescription: "Free random picker — paste your list of names, items, or options and pick a winner instantly. Supports multiple picks and exclusions. No bias, truly random.",
    category: "Generator",
    icon: "Shuffle",
    keywords: ["random picker", "random name picker", "giveaway", "wheel", "random choice", "decision"],
    relatedSlugs: ["coin-flip", "dice-roller", "uuid-generator"],
    isNew: true,
  },
  {
    slug: "morse-code",
    name: "Morse Code Translator",
    description: "Convert text to Morse code and Morse code back to text.",
    metaDescription: "Free Morse code translator — convert any text to dots and dashes instantly, or decode Morse code back to text. Includes audio playback and speed control.",
    category: "Generator",
    icon: "Radio",
    keywords: ["morse code", "translator", "encode", "decode", "dots dashes", "telegraph"],
    relatedSlugs: ["binary-hex", "base64", "fancy-text"],
    isNew: true,
  },

  // ─── Phase 3 — Image ─────────────────────────────────────────────────────
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert any image to a Base64 string or data URL.",
    metaDescription: "Free image to Base64 converter — upload any image and get the Base64 encoded string or data URL instantly. Also decodes Base64 back to image. No upload to server.",
    category: "Image",
    icon: "Binary",
    keywords: ["image to base64", "base64 image", "data url", "encode", "embed", "img src"],
    relatedSlugs: ["base64", "image-convert", "image-compress"],
    isNew: true,
  },
  {
    slug: "exif-viewer",
    name: "EXIF Data Viewer",
    description: "View and remove EXIF metadata from your photos instantly.",
    metaDescription: "Free EXIF viewer — see hidden metadata in your photos including GPS location, camera model, date, aperture, and shutter speed. Remove EXIF for privacy. No upload.",
    category: "Image",
    icon: "Info",
    keywords: ["exif", "metadata", "photo", "gps", "camera", "privacy", "jpeg", "png"],
    relatedSlugs: ["image-compress", "image-convert", "image-resize"],
    isNew: true,
  },
  {
    slug: "image-flipper",
    name: "Image Flip & Rotate",
    description: "Flip images horizontally or vertically, rotate by any angle.",
    metaDescription: "Free image flip and rotate tool — flip your image horizontally or vertically, or rotate it by 90, 180, 270 degrees or a custom angle. Works with JPG, PNG, WebP.",
    category: "Image",
    icon: "FlipHorizontal",
    keywords: ["flip image", "rotate image", "mirror", "horizontal", "vertical", "jpg", "png"],
    relatedSlugs: ["image-crop", "image-resize", "image-compress"],
    isNew: true,
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG Converter",
    description: "Convert SVG files to PNG at any resolution.",
    metaDescription: "Free SVG to PNG converter — convert any SVG vector file to PNG at custom resolution. Set width, height, and background color. Instant, no upload to server.",
    category: "Image",
    icon: "VectorSquare",
    keywords: ["svg to png", "svg converter", "vector to image", "rasterize", "svg png"],
    relatedSlugs: ["image-convert", "image-resize", "image-to-base64"],
    isNew: true,
  },

  // ─── Phase 3 — Health ────────────────────────────────────────────────────
  {
    slug: "body-fat-calculator",
    name: "Body Fat Calculator",
    description: "Calculate body fat percentage using the US Navy method.",
    metaDescription: "Free body fat calculator — estimate body fat percentage using the US Navy method (waist, neck, height measurements). Supports metric and imperial units.",
    category: "Health",
    icon: "Activity",
    keywords: ["body fat", "calculator", "navy method", "bmi", "fitness", "health", "body composition"],
    relatedSlugs: ["bmi-calculator", "calorie-calculator", "water-intake-calculator"],
    isNew: true,
  },
  {
    slug: "sleep-calculator",
    name: "Sleep Cycle Calculator",
    description: "Find the best bedtime or wake-up time based on sleep cycles.",
    metaDescription: "Free sleep calculator — calculate the best time to wake up or go to sleep based on 90-minute sleep cycles. Avoid waking mid-cycle and feel more refreshed.",
    category: "Health",
    icon: "Moon",
    keywords: ["sleep calculator", "sleep cycle", "bedtime", "wake up", "rem", "90 minutes"],
    relatedSlugs: ["age-calculator", "countdown-timer", "calorie-calculator"],
    isNew: true,
  },
  {
    slug: "water-intake-calculator",
    name: "Water Intake Calculator",
    description: "Calculate your recommended daily water intake.",
    metaDescription: "Free water intake calculator — find how much water you should drink daily based on your weight, activity level, and climate. Metric and imperial units supported.",
    category: "Health",
    icon: "Droplets",
    keywords: ["water intake", "hydration", "calculator", "daily water", "drink water", "health"],
    relatedSlugs: ["calorie-calculator", "bmi-calculator", "body-fat-calculator"],
    isNew: true,
  },
  {
    slug: "ovulation-calculator",
    name: "Ovulation Calculator",
    description: "Find your fertile window and estimated ovulation date.",
    metaDescription: "Free ovulation calculator — estimate your ovulation date and fertile window based on your last period and cycle length. Includes a 3-month fertility calendar.",
    category: "Health",
    icon: "Calendar",
    keywords: ["ovulation calculator", "fertile window", "fertility", "period", "pregnancy", "cycle"],
    relatedSlugs: ["due-date-calculator", "date-difference", "age-calculator"],
    isNew: true,
  },

  // ─── Phase 3 — Finance ───────────────────────────────────────────────────
  {
    slug: "retirement-calculator",
    name: "Retirement Calculator",
    description: "Project your retirement savings and estimate your nest egg.",
    metaDescription: "Free retirement calculator — project your retirement savings based on current savings, monthly contributions, return rate, and target age. Includes inflation adjustment.",
    category: "Finance",
    icon: "PiggyBank",
    keywords: ["retirement calculator", "savings", "nest egg", "401k", "pension", "retire"],
    relatedSlugs: ["compound-interest", "investment-return", "mortgage-calculator"],
    isNew: true,
  },
  {
    slug: "tax-bracket-calculator",
    name: "Tax Bracket Calculator",
    description: "Calculate your effective tax rate and tax owed by income bracket.",
    metaDescription: "Free US tax bracket calculator — enter your income to see your effective tax rate, marginal rate, and tax owed by bracket for 2024 federal tax rates.",
    category: "Finance",
    icon: "Landmark",
    keywords: ["tax bracket", "income tax", "effective tax rate", "federal tax", "2024", "marginal rate"],
    relatedSlugs: ["vat-calculator", "discount-calculator", "mortgage-calculator"],
    isNew: true,
  },
  {
    slug: "credit-card-payoff",
    name: "Credit Card Payoff Calculator",
    description: "See how long to pay off your credit card and how much interest you'll pay.",
    metaDescription: "Free credit card payoff calculator — see how long it takes to pay off your balance and total interest paid at different monthly payment amounts. Includes payoff schedule.",
    category: "Finance",
    icon: "CreditCard",
    keywords: ["credit card payoff", "debt calculator", "minimum payment", "interest", "payoff date"],
    relatedSlugs: ["loan-calculator", "mortgage-calculator", "compound-interest"],
    isNew: true,
  },
  {
    slug: "inflation-calculator",
    name: "Inflation Calculator",
    description: "Calculate the inflation-adjusted value of money over time.",
    metaDescription: "Free inflation calculator — find the purchasing power of money over time. Calculate how much $100 in any past year is worth today using historical US CPI data.",
    category: "Finance",
    icon: "TrendingUp",
    keywords: ["inflation calculator", "purchasing power", "cpi", "real value", "cost of living"],
    relatedSlugs: ["compound-interest", "investment-return", "retirement-calculator"],
    isNew: true,
  },

  // ─── Phase 3 — Text ──────────────────────────────────────────────────────
  {
    slug: "duplicate-remover",
    name: "Duplicate Line Remover",
    description: "Remove duplicate lines from any text, keeping only unique lines.",
    metaDescription: "Free duplicate line remover — paste any text and instantly remove duplicate lines. Case-sensitive or insensitive mode. Sort output alphabetically. No upload needed.",
    category: "Text",
    icon: "ListFilter",
    keywords: ["duplicate remover", "remove duplicates", "unique lines", "text cleaner", "dedupe"],
    relatedSlugs: ["line-sorter", "word-counter", "text-diff"],
    isNew: true,
  },
  {
    slug: "line-sorter",
    name: "Line Sorter",
    description: "Sort lines of text alphabetically, by length, numerically, or randomly.",
    metaDescription: "Free line sorter — sort any list alphabetically (A-Z or Z-A), by line length, numerically, or randomly. Remove blanks and duplicates while sorting.",
    category: "Text",
    icon: "ArrowUpDown",
    keywords: ["sort lines", "alphabetical sort", "text sorter", "list sorter", "organize"],
    relatedSlugs: ["duplicate-remover", "word-counter", "case-converter"],
    isNew: true,
  },
  {
    slug: "fancy-text",
    name: "Fancy Text Generator",
    description: "Generate stylish Unicode text — bold, italic, cursive, and more.",
    metaDescription: "Free fancy text generator — convert normal text into bold, italic, cursive, bubble, strikethrough, and 20+ Unicode text styles for Instagram, Twitter, and bios.",
    category: "Text",
    icon: "Type",
    keywords: ["fancy text", "unicode text", "bold text", "italic text", "instagram fonts", "cool text"],
    relatedSlugs: ["case-converter", "morse-code", "lorem-ipsum"],
    isNew: true,
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Convert any text to speech using your browser's built-in voices.",
    metaDescription: "Free text to speech tool — convert any text to audio using browser-native voices. Adjust speed, pitch, and voice. No upload, works offline. Download not required.",
    category: "Text",
    icon: "Volume2",
    keywords: ["text to speech", "tts", "read aloud", "voice", "speech", "audio", "accessibility"],
    relatedSlugs: ["word-counter", "readability-checker", "morse-code"],
    isNew: true,
  },

  // ─── Phase 4 — Developer ─────────────────────────────────────────────────
  {
    slug: "color-contrast-checker",
    name: "Color Contrast Checker",
    description: "Check WCAG AA/AAA color contrast ratios for accessible design.",
    metaDescription: "Free WCAG color contrast checker — verify foreground/background color ratios meet AA and AAA accessibility standards. Real-time ratio, pass/fail badge.",
    category: "Developer",
    icon: "Eye",
    keywords: ["color contrast", "wcag", "accessibility", "a11y", "contrast ratio", "aa", "aaa"],
    relatedSlugs: ["color-picker", "color-converter", "color-palette"],
    isNew: true,
  },
  {
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Build linear and radial CSS gradients visually with live code output.",
    metaDescription: "Free CSS gradient generator — create linear and radial gradients with a visual editor. Copy the CSS code instantly. No sign-up required.",
    category: "Developer",
    icon: "Layers",
    keywords: ["css gradient", "gradient generator", "linear gradient", "radial gradient", "css"],
    relatedSlugs: ["color-picker", "color-converter", "css-minifier"],
    isNew: true,
  },
  {
    slug: "css-shadow-generator",
    name: "CSS Box Shadow Generator",
    description: "Design CSS box shadows visually and copy the ready-to-use CSS.",
    metaDescription: "Free CSS box shadow generator — design shadows with a live visual editor and copy the CSS. Supports multiple layers, inset, blur, spread, and color.",
    category: "Developer",
    icon: "Square",
    keywords: ["css box shadow", "shadow generator", "css shadow", "box-shadow", "css"],
    relatedSlugs: ["css-gradient-generator", "css-minifier", "color-picker"],
    isNew: true,
  },
  {
    slug: "json-schema-validator",
    name: "JSON Schema Validator",
    description: "Validate JSON data against a JSON Schema (draft-07) in your browser.",
    metaDescription: "Free online JSON Schema validator — paste your schema and JSON data to instantly validate and see detailed error messages. Draft-07, 100% client-side.",
    category: "Developer",
    icon: "CheckSquare",
    keywords: ["json schema", "json validator", "schema validation", "draft-07", "ajv", "developer"],
    relatedSlugs: ["json-formatter", "yaml-json", "xml-formatter"],
    isNew: true,
  },
  {
    slug: "cron-builder",
    name: "Cron Expression Builder",
    description: "Build cron expressions visually — select schedule and get the cron string.",
    metaDescription: "Free visual cron expression builder — set minute, hour, day, month, weekday with a UI and get the cron string. Complements the cron parser.",
    category: "Developer",
    icon: "CalendarClock",
    keywords: ["cron builder", "cron expression", "cron schedule", "crontab", "scheduler"],
    relatedSlugs: ["cron-parser", "countdown-timer", "stopwatch"],
    isNew: true,
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator",
    description: "Generate signed JWT tokens with custom headers, payload, and secret.",
    metaDescription: "Free browser-side JWT generator — create signed JWT tokens (HS256/HS384/HS512) with custom headers and payload. No server, no upload, all client-side.",
    category: "Security",
    icon: "KeyRound",
    keywords: ["jwt generator", "json web token", "jwt sign", "hs256", "token", "security"],
    relatedSlugs: ["jwt-decoder", "hash-generator", "password-generator"],
    isNew: true,
  },
  {
    slug: "text-encrypt",
    name: "Text Encryptor / Decryptor",
    description: "Encrypt and decrypt text with AES-256 using the Web Crypto API.",
    metaDescription: "Free AES-256 browser text encryptor — encrypt any text with a password using the Web Crypto API. Decrypt it later. Zero server contact, fully private.",
    category: "Security",
    icon: "LockKeyhole",
    keywords: ["text encrypt", "aes encryption", "encrypt text", "decrypt", "aes-256", "web crypto"],
    relatedSlugs: ["hash-generator", "password-generator", "jwt-generator"],
    isNew: true,
  },

  // ─── Phase 4 — Image ─────────────────────────────────────────────────────
  {
    slug: "color-palette-extractor",
    name: "Image Color Palette Extractor",
    description: "Extract the dominant color palette from any image instantly.",
    metaDescription: "Free image color palette extractor — upload any image and instantly extract the dominant colors as HEX, RGB, and HSL values. 100% browser-side.",
    category: "Image",
    icon: "Pipette",
    keywords: ["color palette", "extract colors", "dominant colors", "image colors", "palette extractor"],
    relatedSlugs: ["color-picker", "color-converter", "color-palette"],
    isNew: true,
  },
  {
    slug: "image-exif-stripper",
    name: "Image EXIF Stripper",
    description: "Remove all EXIF metadata from images before sharing — protect your privacy.",
    metaDescription: "Free EXIF stripper — remove GPS location, camera model, timestamps, and all metadata from images. 100% browser-side, zero upload, download clean image.",
    category: "Image",
    icon: "ShieldOff",
    keywords: ["exif remover", "metadata stripper", "remove exif", "image privacy", "strip metadata"],
    relatedSlugs: ["exif-viewer", "image-compress", "image-convert"],
    isNew: true,
  },
  {
    slug: "ascii-art",
    name: "Image to ASCII Art",
    description: "Convert any image into ASCII art using browser canvas.",
    metaDescription: "Free image to ASCII art converter — upload any image and convert it to ASCII art instantly in your browser. Adjust density and width. Copy or download.",
    category: "Image",
    icon: "AlignLeft",
    keywords: ["ascii art", "image to ascii", "text art", "ascii generator", "character art"],
    relatedSlugs: ["image-convert", "image-resize", "fancy-text"],
    isNew: true,
  },

  // ─── Phase 4 — Math ──────────────────────────────────────────────────────
  {
    slug: "matrix-calculator",
    name: "Matrix Calculator",
    description: "Add, subtract, multiply matrices and compute transpose and determinant.",
    metaDescription: "Free matrix calculator — perform addition, subtraction, multiplication, transpose, and determinant on 2×2 to 4×4 matrices. 100% browser-side.",
    category: "Math",
    icon: "Grid3X3",
    keywords: ["matrix calculator", "matrix multiplication", "determinant", "transpose", "linear algebra"],
    relatedSlugs: ["statistics-calculator", "equation-solver", "scientific-calculator"],
    isNew: true,
  },
  {
    slug: "equation-solver",
    name: "Equation Solver",
    description: "Solve linear, quadratic, and cubic equations step by step.",
    metaDescription: "Free equation solver — solve linear (ax+b=0), quadratic (ax²+bx+c=0), and cubic equations with step-by-step solutions. All client-side.",
    category: "Math",
    icon: "FunctionSquare",
    keywords: ["equation solver", "quadratic formula", "linear equation", "cubic equation", "algebra"],
    relatedSlugs: ["matrix-calculator", "scientific-calculator", "statistics-calculator"],
    isNew: true,
  },
  {
    slug: "prime-factorization",
    name: "Prime Factorization",
    description: "Find the prime factors of any number and compute GCD and LCM.",
    metaDescription: "Free prime factorization tool — enter any integer to get its prime factors, GCD, and LCM. Instant result, all browser-side. No ads on the result.",
    category: "Math",
    icon: "Hash",
    keywords: ["prime factorization", "prime factors", "gcd", "lcm", "number theory", "math"],
    relatedSlugs: ["equation-solver", "scientific-calculator", "number-to-words"],
    isNew: true,
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between any base from 2 to 36 (binary, octal, hex, and more).",
    metaDescription: "Free number base converter — convert integers between any base from 2 (binary) to 36. Supports binary, octal, decimal, hex, and custom bases.",
    category: "Converter",
    icon: "Binary",
    keywords: ["base converter", "number base", "binary", "octal", "hexadecimal", "radix", "base 64"],
    relatedSlugs: ["binary-hex", "roman-numeral", "scientific-calculator"],
    isNew: true,
  },

  // ─── Phase 4 — Finance ───────────────────────────────────────────────────
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description: "Calculate return on investment, net profit, and annualized ROI.",
    metaDescription: "Free ROI calculator — enter initial investment, final value, and time period to get ROI %, net profit, and annualized return. Instant, browser-side.",
    category: "Finance",
    icon: "TrendingUp",
    keywords: ["roi calculator", "return on investment", "profit", "investment return", "annualized roi"],
    relatedSlugs: ["investment-return", "compound-interest", "inflation-calculator"],
    isNew: true,
  },
  {
    slug: "break-even-calculator",
    name: "Break-Even Calculator",
    description: "Calculate the break-even point in units and revenue for your business.",
    metaDescription: "Free break-even calculator — enter fixed costs, variable cost per unit, and selling price to find your break-even point in units and revenue.",
    category: "Finance",
    icon: "BarChart2",
    keywords: ["break even calculator", "break-even point", "fixed costs", "variable costs", "business"],
    relatedSlugs: ["roi-calculator", "loan-calculator", "compound-interest"],
    isNew: true,
  },
  {
    slug: "net-worth-calculator",
    name: "Net Worth Calculator",
    description: "Calculate your net worth by adding assets and subtracting liabilities.",
    metaDescription: "Free net worth calculator — list your assets and liabilities to instantly calculate your net worth. All data stays in your browser, never uploaded.",
    category: "Finance",
    icon: "Wallet",
    keywords: ["net worth calculator", "assets liabilities", "personal finance", "wealth", "balance sheet"],
    relatedSlugs: ["retirement-calculator", "investment-return", "compound-interest"],
    isNew: true,
  },
  {
    slug: "dividend-calculator",
    name: "Dividend Calculator",
    description: "Calculate dividend income, yield, and growth projections.",
    metaDescription: "Free dividend calculator — enter share price, dividend per share, and number of shares to calculate annual income, yield %, and 10-year DRIP projections.",
    category: "Finance",
    icon: "Coins",
    keywords: ["dividend calculator", "dividend yield", "dividend income", "drip", "stock dividend"],
    relatedSlugs: ["investment-return", "compound-interest", "roi-calculator"],
    isNew: true,
  },

  // ─── Phase 4 — Health ────────────────────────────────────────────────────
  {
    slug: "ideal-weight-calculator",
    name: "Ideal Weight Calculator",
    description: "Calculate your ideal body weight using 5 different medical formulas.",
    metaDescription: "Free ideal weight calculator — uses Hamwi, Devine, Robinson, Miller, and BMI methods to estimate your ideal weight in kg and lbs. Metric and imperial.",
    category: "Health",
    icon: "Scale",
    keywords: ["ideal weight", "ideal body weight", "ibw", "healthy weight", "hamwi", "devine"],
    relatedSlugs: ["bmi-calculator", "body-fat-calculator", "calorie-calculator"],
    isNew: true,
  },
  {
    slug: "macro-calculator",
    name: "Macro Calculator",
    description: "Calculate your daily protein, carbs, and fat targets based on your goals.",
    metaDescription: "Free macro calculator — enter your stats and fitness goal to get personalized daily protein, carbohydrate, and fat targets in grams and calories.",
    category: "Health",
    icon: "Beef",
    keywords: ["macro calculator", "macros", "protein calculator", "carbs fat protein", "iifym", "fitness"],
    relatedSlugs: ["calorie-calculator", "bmi-calculator", "water-intake-calculator"],
    isNew: true,
  },
  {
    slug: "heart-rate-zones",
    name: "Heart Rate Zone Calculator",
    description: "Calculate your 5 heart rate training zones based on your max heart rate.",
    metaDescription: "Free heart rate zone calculator — enter your age or max HR to get all 5 training zones (warm-up through max). Supports Karvonen method with resting HR.",
    category: "Health",
    icon: "HeartPulse",
    keywords: ["heart rate zones", "hr zones", "max heart rate", "training zones", "cardio", "karvonen"],
    relatedSlugs: ["bmi-calculator", "calorie-calculator", "macro-calculator"],
    isNew: true,
  },

  // ─── Phase 4 — Text ──────────────────────────────────────────────────────
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown Converter",
    description: "Convert HTML markup to clean Markdown text instantly.",
    metaDescription: "Free HTML to Markdown converter — paste any HTML and get clean, readable Markdown output instantly. Handles headings, lists, links, tables, and code.",
    category: "Text",
    icon: "FileCode",
    keywords: ["html to markdown", "html markdown", "convert html", "markdown converter", "html parser"],
    relatedSlugs: ["markdown-html", "xml-formatter", "html-entities"],
    isNew: true,
  },
  {
    slug: "decision-matrix",
    name: "Decision Matrix",
    description: "Evaluate options against weighted criteria to make better decisions.",
    metaDescription: "Free decision matrix tool — add your options and weighted criteria, score each one, and instantly see which choice scores highest. All browser-side.",
    category: "Math",
    icon: "LayoutGrid",
    keywords: ["decision matrix", "weighted decision", "decision analysis", "criteria matrix", "choice"],
    relatedSlugs: ["statistics-calculator", "grade-calculator", "percentage-calculator"],
    isNew: true,
  },
];

export const categories: ToolCategory[] = [
  "PDF",
  "Image",
  "Calculator",
  "Converter",
  "Text",
  "Generator",
  "Security",
  "Developer",
  "Health",
  "Finance",
  "Math",
];

export const categoryColors: Record<ToolCategory, string> = {
  PDF:        "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
  Image:      "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
  Calculator: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
  Converter:  "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
  Text:       "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
  Generator:  "bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400",
  Security:   "bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-400",
  Developer:  "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400",
  Health:     "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-400",
  Finance:    "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400",
  Math:       "bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-400",
};

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((t) => t.category === category);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase().trim();
  if (!q) return tools;
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.includes(q))
  );
}
